INSERT INTO CUSTOMER(USERNAME, PASSWORD) VALUES ('erika.muller29@gmail.com', '$2a$11$2i4zzsHoVnPlfmivSp11Ae38tO/tPQSzHUMsBS19tP8v6AoaIl82K');
INSERT INTO CUSTOMER(USERNAME, PASSWORD) VALUES ('tom.jeff@gmail.com', '$2a$11$/G2At6pqlzIri.2n2bixqO.NZo1bFqMTKBhoA.7SOSVlK7MzgcV8C');


INSERT INTO CUSTOMER_DETAILS(USERNAME, FIRST_NAME, LAST_NAME) VALUES ('erika.muller29@gmail.com','Erika','Muller');
INSERT INTO CUSTOMER_DETAILS(USERNAME, FIRST_NAME, LAST_NAME) VALUES ('tom.jeff@gmail.com','Tom','Jeff');

INSERT INTO AUTH_GROUP (USERNAME, AUTH_GROUP) VALUES('erika.muller29@gmail.com', 'ADMIN');
INSERT INTO AUTH_GROUP (USERNAME, AUTH_GROUP) VALUES('tom.jeff@gmail.com', 'USER');