CREATE SEQUENCE IF NOT EXISTS seq_users
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE SEQUENCE IF NOT EXISTS seq_user_details
MINVALUE 1
START WITH 1
INCREMENT BY 1
CACHE 10;

CREATE TABLE USER (
  ID BIGINT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL UNIQUE,
  PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE USER_DETAILS (
  ID BIGINT PRIMARY KEY,
  USER_ID BIGINT NOT NULL UNIQUE,
  USERNAME VARCHAR(128) NOT NULL UNIQUE,
  FIRST_NAME VARCHAR(128) NOT NULL,
  LAST_NAME VARCHAR(128) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL UNIQUE,
);

ALTER TABLE USER_DETAILS ADD CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE;

INSERT INTO USER(ID, USERNAME, PASSWORD) VALUES (seq_users.nextval, 'erika.muller29', 'pass1');
INSERT INTO USER_DETAILS(ID, USER_ID, USERNAME, FIRST_NAME, LAST_NAME, EMAIL) VALUES (seq_users_details.nextval, 1, 's','sf', 'a@gmail.com');