CREATE TABLE USER (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL UNIQUE,
  PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE USER_DETAILS (
  ID BIGINT AUTO_INCREMENT,
  USERNAME VARCHAR(128) NOT NULL,
  FIRST_NAME VARCHAR(128) NOT NULL,
  LAST_NAME VARCHAR(128) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL UNIQUE,
);

ALTER TABLE USER_DETAILS ADD CONSTRAINT FK_USER FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME) ON DELETE CASCADE;