CREATE TABLE USER (
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL UNIQUE,
  PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE USER_DETAILS (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(128) NOT NULL UNIQUE,
  FIRST_NAME VARCHAR(128) NOT NULL,
  LAST_NAME VARCHAR(128) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE AUTH_GROUP (
   GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
   USERNAME VARCHAR(128) NOT NULL UNIQUE,
   AUTH_GROUP VARCHAR(128) NOT NULL UNIQUE,
   CONSTRAINT AUTH_GROUP_FK FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME)
);